# Site
name: "Rishabh Singh"
title: "Teaching Assistant at University of Maryland, College Park"
description: "I am a student of professional master's in Robotics and Systems Engineering at the University of Maryland, College Park, with a background in 
Automotive, and Mechanical Engineering and Project Management. A highly self-motivated individual with 2 Indian patent filings and an SAE publication who 
believes that technological innovation can solve every problem that exists and can impact the world for good. An entrepreneur by heart who is passionate 
about solving real-world problems to make this world a better place! And always happy to expand my horizon to achieve the same.
My experience includes leading a collegiate ATV designing project like SAE Baja, launching real‑world products like Mahindra Marazzo, creating a B‑plan for a 
startup, and leading an international novel project to monitor river water quality funded by IUSSTF (Indo‑US Science and Technology Forum). After a couple of 
years of experience in the automotive industry, I decided to explore a new field like Robotics to extend my capabilities as an engineer. As a result, my learning 
curve was high during the first semester, but I de‑ livered the projects and assignments on time and in quality. What challenged me was hard work, perseverance, 
and conviction to learn and apply. 
According to my experience, there is a slight chance for a product going wrong, if the team behind it has the capabilities mentioned above. In contrast, one can 
develop technical skills with time and effort. As mentioned above, I am always willing to expand my horizon if required and if I get to learn something new and 
contribute along the way."
logo: 'assets/images/favicon.png'
email: rsingh24@umd.edu
medium: https://medium.com/@s.vinouze
twitter: https://twitter.com/stephenvinouze
linkedin: https://www.linkedin.com/in/rishabh-singh2911/
github: https://github.com/rish2911
favicon: 'assets/images/favicon.png'
baseurl:
google_analytics: 'UA-166933112-1'
disqus: 'stephenvinouze'
mailchimp-list: 'https://stephenvinouze.us18.list-manage.com/subscribe?u=f1f3eb2d7ae0213227f09dd2c&id=1f16cf654c'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  stephen:
    name: Stephen Vinouze
    display_name: Stephen Vinouze
    avatar: 'assets/images/avatar.png'
    email: s.vinouze@gmail.com
    web: https://medium.com/@s.vinouze
    twitter: https://twitter.com/stephenvinouze

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
